### ISSUE TITLE
We live in a dystopian future in which no-one may ascend closer to the surface. We are forever burrowing closer to the tempting oblivion of the underworld.

### ISSUE THREAD

**Issue by carrutstick** [apsillers/Taggem#2]

**Comment by apsillers** [comment]
Fixed in https://github.com/apsillers/Taggem/commit/4fde751b9ee47dc662c4d2972985852965ec80f3

**Comment by apsillers** [comment]
We now merely live in a dystopian future where grid bugs and SCP-096 try to kill us at every turn. But, hey, at least we have stairs!

**Comment by blarblar** [comment]
STAIRS.

I think that commit never made it off my computer.

On Sun, Dec 8, 2013 at 7:12 PM, Andrew Sillers notifications@github.comwrote:

> We now merely live in a dystopian future where grid bugs and SCP-096 try
> to kill us at every turn. But, hey, at least we have stairs!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/apsillers/Taggem/issues/2#issuecomment-30097473
> .

## 

Max Morawski
Lecturer
University of Maryland, Baltimore County
1000 Hilltop Circle
ITE 215
(410) 455-8867
